name: esda
channels:
  - conda-forge
dependencies:
  - python
  # required
  - geopandas
  - libpysal>=4.12
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - shapely
  # optional, testing, etc.
  - folium
  - mapclassify
  - matplotlib
  - numba
  - rtree
